#!/usr/bin/env python3
import os
from writer_helper import write_strings_xml

# 1. Spanish (es)
es = {
    "app_name": "Horizon TV",
    "common_warning": "Advertencia",
    "common_refresh": "Actualizar",
    "common_search": "Buscar",
    "common_clear": "Borrar",
    "common_city": "Ciudad",
    "common_favorite": "Favorito",
    "common_close": "Cerrar",
    "common_play_pause": "Reproducir o pausar",
    "common_live": "EN VIVO",
    "common_active": "ACTIVO",
    "unit_kmh": "km/h",
    "unit_mph": "mph",
    "nav_home": "Inicio",
    "nav_live_tv": "TV en Vivo",
    "nav_forecast": "Pronóstico",
    "nav_radar": "Radar",
    "nav_search": "Búsqueda",
    "nav_vod": "VOD Hub",
    "nav_settings": "Ajustes",
    "brand_title": "Horizon",
    "brand_subtitle": "Weather TV",
    "badge_live_24_7": "EN VIVO 24/7",
    "header_telemetry_status": "Telemetría meteorológica continua",
    "header_remote": "Control Remoto",
    "header_active_alert": "ALERTA ACTIVA",
    "lbar_badge_live": "EN VIVO",
    "lbar_title": "HORIZON L-BAR",
    "lbar_ch": "CANAL 104",
    "lbar_channel_tag": "CH 104 • TRANSMISIÓN EN VIVO 24/7",
    "lbar_collapse": "CONTRAER",
    "lbar_expand": "L-BAR",
    "lbar_feels_like": "Sensación %1$s",
    "lbar_wind": "Viento",
    "lbar_humidity": "Humedad",
    "lbar_barometer": "Barómetro",
    "lbar_dew_point": "Punto de rocío",
    "lbar_aqi": "ICA",
    "lbar_uv_index": "Índice UV",
    "lbar_visibility": "Visibilidad",
    "lbar_diurnal_outlook": "PANORAMA DIURNO",
    "lbar_dispatch_title": "BOLETÍN HORIZON",
    "lbar_horizon_dispatch": "BOLETÍN HORIZON",
    "lbar_default_ticker": "SENSORES METEOROLÓGICOS NOMINALES • TRANSMISIÓN CONTINUA DOPPLER 24/7 • SIN ALERTAS ACTIVAS",
    "lbar_rain_suffix": "%1$d%% Lluvia",
    "emergency_broadcast": "TRANSMISIÓN DE EMERGENCIA",
    "emergency_exp": "EXP: %1$s",
    "emergency_safety_protocol": "PROTOCOLO DE SEGURIDAD",
    "emergency_dismiss": "Descartar",
    "emergency_bulletin": "BOLETÍN DE %1$s",
    "emergency_telemetry_title": "TELEMETRÍA METEOROLÓGICA",
    "emergency_safety_title": "DEFENSA CIVIL E INSTRUCCIONES DE SEGURIDAD",
    "emergency_effective": "Efectivo: %1$s",
    "emergency_expires": "Expira: %1$s",
    "emergency_acknowledge": "CONFIRMAR Y VOLVER A LA TRANSMISIÓN",
    "alert_warning": "Advertencia",
    "alert_bulletin": "BOLETÍN DE %1$s",
    "alert_meteorological_telemetry": "TELEMETRÍA METEOROLÓGICA",
    "alert_civil_defense": "DEFENSA CIVIL E INSTRUCCIONES DE SEGURIDAD",
    "alert_effective": "Efectivo: %1$s",
    "alert_acknowledge_advisory": "CONFIRMAR Y VOLVER A LA TRANSMISIÓN",
    "alert_test_title": "BOLETÍN DE PRUEBA: LÍNEA DE TURBONADA SEVERA",
    "alert_test_summary": "Esta es una prueba certificada de la Red de Transmisión Meteorológica de Emergencia de Horizon TV. Sensores atmosféricos han detectado vientos simulados de 115 km/h con granizo de 45 mm.",
    "alert_test_instructions": "Refúgiese de inmediato en una habitación interior en el piso más bajo. Aléjese de las ventanas. Manténgase en sintonía con Horizon TV 24/7.",
    "pip_live": "PiP EN VIVO",
    "pip_mute": "Silenciar",
    "pip_expand": "Expandir",
    "pip_close": "Cerrar",
    "remote_title": "CONTROL REMOTO TV",
    "remote_close": "Cerrar control",
    "remote_up": "Arriba",
    "remote_down": "Abajo",
    "remote_left": "Izquierda",
    "remote_right": "Derecha",
    "remote_dpad_up": "Arriba",
    "remote_dpad_down": "Abajo",
    "remote_dpad_left": "Izquierda",
    "remote_dpad_right": "Derecha",
    "remote_ok": "Aceptar",
    "remote_home": "Inicio",
    "remote_live_tv": "TV en Vivo",
    "remote_radar": "Radar",
    "remote_search": "Buscar",
    "remote_quick_channels": "CANALES RÁPIDOS DE TELEVISIÓN",
    "remote_instructions": "Utilice las flechas del D-Pad y OK para controlar la pantalla a distancia",
    "home_live_conditions": "Condiciones meteorológicas en vivo",
    "home_last_updated": "Última actualización: %1$s",
    "home_wind_gusts": "Ráfagas de viento",
    "home_uv_index_label": "Índice UV",
    "home_active_alert_banner_prefix": "ALERTA ACTIVA:",
    "home_hourly_synoptic_strip": "LÍNEA TEMPORAL SINÓPTICA DE 12 HORAS",
    "home_saved_stations": "ESTACIONES GUARDADAS",
    "home_manage_stations": "GESTIONAR",
    "home_vod_featured": "REPORTAJES DESTACADOS VOD",
    "home_view_all_vod": "VER TODO VOD",
    "home_view_protocol": "VER PROTOCOLO",
    "home_card_radar_title": "Radar Doppler Dual-Pol",
    "home_card_radar_desc": "Barrido Doppler de reflectividad en vivo",
    "home_badge_layers": "4 CAPAS",
    "home_card_forecast_title": "Pronóstico a 14 días",
    "home_card_forecast_desc": "Modelos sinópticos detallados",
    "home_badge_days": "14 DÍAS",
    "home_card_vod_title": "Archivo de campo VOD",
    "home_card_vod_desc": "Caza de tormentas y estudios climáticos",
    "home_badge_vod": "VOD 1080P",
    "home_carousel_title": "PROGRAMACIÓN Y ROTACIÓN DE RADAR",
    "home_carousel_switch": "CAMBIAR VISTA",
    "home_featured_stories": "INVESTIGACIONES DE CAMPO DESTACADAS",
    "home_all_stories": "TODOS LOS REPORTAJES",
    "home_live_badge": "AL AIRE",
    "home_studio_center": "Centro de Comando de Estudio Horizon TV • Operaciones Nacionales de Radar",
    "home_meteorologist_duty": "METEORÓLOGO DE TURNO",
    "home_continuous_broadcast": "Transmisión continua de radar y telemetría multirregional",
    "home_switch_broadcast": "CAMBIAR VISTA DE TRANSMISIÓN",
    "home_presented_by": "PRESENTADO POR LA DRA. SARAH CHEN",
    "home_news_ticker_prefix": "NOTICIAS EN VIVO",
    "home_local_microclimate": "TELEMETRÍA DE MICROCLIMA LOCAL",
    "home_now_badge": "AHORA",
    "home_feels_like": "Sensación %1$s",
    "home_wind_label": "Velocidad del viento",
    "home_humidity_label": "Humedad",
    "home_aqi_label": "Calidad del aire",
    "home_diurnal_breakdown": "DESGLOSE DIURNO (PRÓXIMAS 12 HORAS)",
    "home_rain_chance": "Lluvia %1$d%%",
    "home_wind": "Viento",
    "home_humidity": "Humedad",
    "home_barometer": "Barómetro",
    "home_dew_point": "Punto de rocío",
    "home_air_quality": "Calidad del aire",
    "home_audio": "Audio",
    "forecast_title": "Pronóstico atmosférico sinóptico y microtelemetría",
    "forecast_subtitle": "Proyecciones completas a 14 días, curvas horarias y datos de microsensores en tiempo real",
    "forecast_tab_five_day": "Pronóstico 5 días",
    "forecast_tab_hourly": "Tendencias 24h",
    "forecast_tab_astronomy": "Celestial y Lunar",
    "forecast_tab_telemetry": "Telemetría en Vivo",
    "forecast_tab_extended": "Panorama 14 días",
    "forecast_fourteen_day_header": "PANORAMA METEOROLÓGICO EXTENDIDO DE 14 DÍAS",
    "forecast_meteorological_outlook": "PANORAMA METEOROLÓGICO",
    "forecast_numerical_prediction": "Modelos de predicción numérica y telemetría en tiempo real",
    "forecast_tab_5day": "Pronóstico 5 días",
    "forecast_tab_36hour": "Tendencias 24h",
    "forecast_tab_24hour": "Celestial / Luna",
    "forecast_tab_14day": "14 Días Extendido",
    "forecast_rain_risk": "Probabilidad de precipitación",
    "forecast_atmospheric_deepdive": "ANÁLISIS PROFUNDO DE TELEMETRÍA ATMOSFÉRICA",
    "forecast_relative_humidity": "Humedad relativa",
    "forecast_dew_point": "Punto de rocío",
    "forecast_surface_pressure": "Presión superficial",
    "forecast_high_pressure": "Alta presión • Despejado",
    "forecast_low_pressure": "Baja presión • Alerta de tormenta",
    "forecast_uv_index": "Radiación solar UV",
    "forecast_uv_of_11": "de 11+ en índice",
    "forecast_uv_very_high": "Radiación muy alta",
    "forecast_uv_high": "Radiación alta",
    "forecast_uv_moderate": "Moderada",
    "forecast_uv_low": "Baja / Segura",
    "forecast_wind_gust_vector": "Vector de viento y ráfagas",
    "forecast_peak_gusts": "Ráfagas máximas: %1$s",
    "forecast_atmospheric_visibility": "Visibilidad atmosférica",
    "forecast_clear_horizon": "Horizonte despejado",
    "forecast_reduced_visibility": "Visibilidad reducida",
    "forecast_cloud_cover": "Cobertura de nubes",
    "forecast_sky_observation": "Observación del cielo",
    "forecast_granular_table": "TABLA DETALLADA DEL MODELO A 5 DÍAS",
    "forecast_hum": "Hum: %1$d%%",
    "forecast_14day_extended": "PANORAMA METEOROLÓGICO EXTENDIDO DE 14 DÍAS",
    "forecast_rain": "Lluvia %1$d%%",
    "radar_title": "Radar Doppler Dual-Pol interactivo",
    "radar_subtitle": "Telemetría en vivo y reflectividad • Estación: KOKX NEXRAD • Centrado en %1$s",
    "radar_layer_precip": "Precipitación",
    "radar_layer_traffic": "Corredores de tráfico",
    "radar_layer_satellite": "Satélite IR",
    "radar_layer_wind": "Líneas de viento",
    "radar_legend_precip_title": "REFLECTIVIDAD (dBZ)",
    "radar_legend_traffic_title": "VELOCIDADES DE TRÁFICO",
    "radar_legend_satellite_title": "TEMPERATURA DE NUBES IR",
    "radar_legend_wind_title": "VELOCIDAD DE LÍNEA",
    "radar_legend_precip_light": "20-30 dBZ (Lluvia ligera)",
    "radar_legend_precip_mod": "35-45 dBZ (Moderada)",
    "radar_legend_precip_heavy": "50-60 dBZ (Fuerte/Tormenta)",
    "radar_legend_precip_hail": "65+ dBZ (Peligro de granizo)",
    "radar_legend_traffic_fast": "65+ mph (Flujo rápido)",
    "radar_legend_traffic_mod": "35-50 mph (Moderado)",
    "radar_legend_traffic_slow": "< 20 mph (Congestión severa)",
    "radar_legend_sat_cirrus": "-20°C (Cirros)",
    "radar_legend_sat_frontal": "-45°C (Nubes frontales)",
    "radar_legend_sat_core": "-65°C (Núcleo convectivo profundo)",
    "radar_legend_wind_vector": "Dirección y velocidad del vector",
    "radar_zoom_in": "Acercar",
    "radar_zoom_out": "Alejar",
    "radar_recenter": "Recentrar",
    "livetv_next_periods": "PRÓXIMOS PERIODOS DE TRANSMISIÓN",
    "livetv_live_broadcast": "TRANSMISIÓN EN VIVO",
    "livetv_doppler_specs": "DOPPLER DUAL-POL EN VIVO 500KW",
    "livetv_audio_on": "AUDIO ACTIVADO",
    "livetv_muted": "SILENCIADO",
    "livetv_pip_mode": "MODO PiP",
    "livetv_presenter_name": "PRESENTADORA: DRA. SARAH CHEN",
    "livetv_presenter_subtitle": "Centro Nacional de Comando de Radar Meteorológico • Telemetría Doppler en Vivo",
    "search_header_title": "Búsqueda de estaciones meteorológicas globales",
    "search_header_subtitle": "Acceda a radar y telemetría en vivo de más de 200,000 municipios globales",
    "search_placeholder": "Ingrese ciudad, estado o país (ej. Tokio, Londres, Madrid)...",
    "search_gps_button": "AUTODETECTAR GPS",
    "search_results_title": "RESULTADOS DE BÚSQUEDA (%1$d)",
    "search_no_results": "No se encontraron estaciones meteorológicas para \"%1$s\"",
    "search_saved_title": "ESTACIONES FAVORITAS GUARDADAS (%1$d)",
    "search_saved_subtitle": "GUARDADO EN PERFIL LOCAL",
    "search_active_badge": "ACTIVO",
    "settings_header_title": "Preferencias de transmisión y configuración",
    "settings_header_subtitle": "Personalice la presentación de TV, unidades meteorológicas y fuentes de telemetría",
    "settings_cat_display": "ESTÉTICA DE PANTALLA Y TRANSMISIÓN",
    "settings_crt_title": "Líneas de escaneo CRT y viñeta cinematográfica",
    "settings_crt_subtitle": "Auténtico efecto retro de haz CRT de televisión y oscurecimiento en bordes",
    "settings_remote_title": "Superposición de control remoto virtual",
    "settings_remote_subtitle": "Habilitar D-Pad flotante para navegación optimizada para TV",
    "settings_cat_units": "UNIDADES METEOROLÓGICAS Y ESCALAS",
    "settings_units_title": "Unidades de temperatura y atmósfera",
    "settings_units_subtitle": "Las preferencias se guardan localmente y se conservan entre sesiones",
    "settings_saved_locally": "GUARDADO LOCALMENTE",
    "settings_celsius_title": "Celsius (°C)",
    "settings_celsius_subtitle": "Métrico: °C, km/h, mm, hPa",
    "settings_fahrenheit_title": "Fahrenheit (°F)",
    "settings_fahrenheit_subtitle": "Imperial: °F, mph, in, inHg",
    "settings_cat_audio": "CONTROLES DE AUDIO Y TRANSMISIÓN",
    "settings_audio_title": "Transmisión de audio en vivo 24/7",
    "settings_audio_subtitle": "Audio atmosférico de fondo y comentarios de meteorólogos",
    "settings_cat_civil": "DEFENSA CIVIL Y PROTOCOLOS DE EMERGENCIA",
    "settings_ebs_title": "Prueba del Sistema de Transmisión de Emergencia (EBS)",
    "settings_ebs_subtitle": "Simular modal urgente de advertencia de tornado/tormenta severa",
    "settings_ebs_btn": "ACTIVAR PRUEBA",
    "settings_cat_system": "SISTEMA Y FUENTES DE TELEMETRÍA",
    "settings_sys_platform": "Motor de plataforma",
    "settings_sys_provider": "Proveedor principal",
    "settings_sys_radar": "Núcleo de radar",
    "settings_sys_astronomy": "Cálculo astronómico",
    "settings_sys_interval": "Intervalo de transmisión de emergencia",
    "vod_title": "ARCHIVO DE VIDEO BAJO DEMANDA (VOD) HORIZON",
    "vod_subtitle": "Investigaciones meteorológicas de campo especiales, persecuciones de tormentas y reportes climáticos",
    "vod_badge_4k": "TRANSMISIÓN 4K / 1080P",
    "vod_quality_badge": "TRANSMISIÓN 4K / 1080P",
    "vod_more_category": "MÁS EN ESTA CATEGORÍA",
    "vod_more_in_category": "MÁS EN ESTA CATEGORÍA",
    "vod_streaming_status": "TRANSMITIENDO ENLACE MAESTRO 1080P",
    "vod_streaming_feed": "TRANSMITIENDO ENLACE MAESTRO 1080P",
    "vod_paused_status": "PAUSADO",
    "vod_paused": "PAUSADO",
    "vod_produced_by": "PRODUCIDO POR HORIZON NETWORKS",
    "vod_published": "PUBLICADO: %1$s",
    "vod_cat_all": "Todos los boletines",
    "vod_cat_severe": "Clima severo",
    "vod_cat_forecasts": "Pronósticos",
    "vod_cat_science": "Ciencias de la Tierra",
    "vod_cat_earth_sci": "Ciencias de la Tierra",
    "vod_cat_climate": "Clima y Naturaleza",
    "astro_title": "HORIZONTE CELESTIAL Y LUNAR",
    "astro_synodic": "CICLO SINÓDICO REAL",
    "astro_sunrise": "Amanecer %1$s",
    "astro_sunset": "Atardecer %1$s",
    "astro_daylight_progress": "Progreso de luz diurna: %1$d%% del arco solar transcurrido",
    "astro_night_horizon": "Horizonte nocturno: el Sol está bajo el horizonte local",
    "astro_illumination": "%1$d%% Iluminación",
    "astro_days_to_full": "%1$d días hasta la próxima Luna Llena",
    "telemetry_header_title": "TELEMETRÍA DE SENSORES ATMOSFÉRICOS EN TIEMPO REAL",
    "telemetry_live_status": "Flujo local en vivo • Muestreo activo (cada 2.0s) • Ciclo #%1$d",
    "telemetry_paused_status": "Flujo de telemetría pausado",
    "telemetry_btn_pause": "PAUSAR",
    "telemetry_btn_resume": "REANUDAR",
    "telemetry_temperature": "TEMPERATURA",
    "telemetry_humidity": "HUMEDAD",
    "telemetry_barometer": "BARÓMETRO",
    "telemetry_temp_chilly": "Fresco / Frío",
    "telemetry_temp_mild": "Confort templado",
    "telemetry_temp_warm": "Cálido",
    "telemetry_temp_heat": "Calor intenso",
    "telemetry_hum_dry": "Aire seco",
    "telemetry_hum_ideal": "Confort ideal",
    "telemetry_hum_humid": "Húmedo",
    "telemetry_hum_high": "Alta humedad",
    "telemetry_press_low": "Baja (Vigilancia de tormenta)",
    "telemetry_press_normal": "Normal (Estable)",
    "telemetry_press_high": "Alta (Cielos despejados)",
    "recharts_badge": "VISUALIZACIÓN DE GRÁFICOS",
    "recharts_title": "PRONÓSTICO METEOROLÓGICO SINÓPTICO DE 5 DÍAS",
    "recharts_subtitle": "Gradientes de temperatura de curva de área, cuadrícula cartesiana y barras de precipitación",
    "recharts_tab_all": "TODO",
    "recharts_tab_temp": "TEMP",
    "recharts_tab_rain": "LLUVIA",
    "recharts_today": "HOY",
    "recharts_legend_high": "Curva de temp máx (%1$s)",
    "recharts_legend_low": "Curva de temp mín (%1$s)",
    "recharts_legend_pop": "Probabilidad de lluvia (POP %%)",
    "recharts_hint": "HAGA CLIC EN CUALQUIER DÍA PARA VER DETALLES",
    "trends_title": "Curva de temperatura y precipitación de 24 horas",
    "trends_temp_legend": "Temp (%1$s)",
    "trends_rain_legend": "POP lluvia (%%)",
    "loading_sync": "SINCRONIZANDO TELEMETRÍA DE TRANSMISIÓN HORIZON...",
    "loading_connecting": "Conectando a redes Open-Meteo y Radar Doppler",
    "error_signal_interrupted": "Señal de transmisión interrumpida",
    "error_reconnect_button": "RECONECTAR TELEMETRÍA"
}

# 2. French (fr)
fr = {k: v for k, v in es.items()}
fr.update({
    "common_warning": "Avertissement",
    "common_refresh": "Actualiser",
    "common_search": "Rechercher",
    "common_clear": "Effacer",
    "common_city": "Ville",
    "common_favorite": "Favori",
    "common_close": "Fermer",
    "common_play_pause": "Lecture ou pause",
    "common_live": "EN DIRECT",
    "common_active": "ACTIF",
    "nav_home": "Accueil",
    "nav_live_tv": "TV en Direct",
    "nav_forecast": "Prévisions",
    "nav_radar": "Radar",
    "nav_search": "Recherche",
    "nav_vod": "Hub VOD",
    "nav_settings": "Paramètres",
    "badge_live_24_7": "EN DIRECT 24/7",
    "header_telemetry_status": "Télémétrie météorologique continue",
    "header_remote": "Télécommande",
    "header_active_alert": "ALERTE ACTIVE",
    "lbar_badge_live": "EN DIRECT",
    "lbar_ch": "CANAL 104",
    "lbar_channel_tag": "CH 104 • FLUX EN DIRECT HORIZON 24/7",
    "lbar_collapse": "RÉDUIRE",
    "lbar_expand": "L-BAR",
    "lbar_feels_like": "Ressenti %1$s",
    "lbar_wind": "Vent",
    "lbar_humidity": "Humidité",
    "lbar_barometer": "Baromètre",
    "lbar_dew_point": "Point de rosée",
    "lbar_aqi": "IQA",
    "lbar_uv_index": "Indice UV",
    "lbar_visibility": "Visibilité",
    "lbar_diurnal_outlook": "APERÇU DIURNE",
    "lbar_dispatch_title": "BULLETIN HORIZON",
    "lbar_horizon_dispatch": "BULLETIN HORIZON",
    "lbar_default_ticker": "CAPTEURS MÉTÉOROLOGIQUES NOMINAUX • DIFFUSION DOPPLER CONTINUE 24/7 • AUCUNE ALERTE EN COURS",
    "lbar_rain_suffix": "%1$d%% Pluie",
    "emergency_broadcast": "DIFFUSION D'URGENCE",
    "emergency_safety_protocol": "PROTOCOLE DE SÉCURITÉ",
    "emergency_dismiss": "Ignorer",
    "emergency_bulletin": "BULLETIN %1$s",
    "emergency_telemetry_title": "TÉLÉMÉTRIE MÉTÉOROLOGIQUE",
    "emergency_safety_title": "SÉCURITÉ CIVILE & INSTRUCTIONS",
    "emergency_effective": "En vigueur: %1$s",
    "emergency_expires": "Expire: %1$s",
    "emergency_acknowledge": "CONFIRMER & REVENIR AU DIRECT",
    "alert_warning": "Avertissement",
    "alert_bulletin": "BULLETIN %1$s",
    "alert_meteorological_telemetry": "TÉLÉMÉTRIE MÉTÉOROLOGIQUE",
    "alert_civil_defense": "SÉCURITÉ CIVILE & INSTRUCTIONS",
    "alert_effective": "En vigueur: %1$s",
    "alert_acknowledge_advisory": "CONFIRMER & REVENIR AU DIRECT",
    "alert_test_title": "TEST BULLETIN D'URGENCE: LIGNE DE GRAINS",
    "alert_test_summary": "Ceci est un test certifié du réseau d'urgence météorologique Horizon TV. Rafales simulées à 115 km/h et grêle de 45 mm détectées.",
    "alert_test_instructions": "Abritez-vous immédiatement dans une pièce intérieure au niveau le plus bas. Éloignez-vous des fenêtres. Restez à l'écoute d'Horizon TV 24/7.",
    "pip_live": "PiP EN DIRECT",
    "pip_mute": "Muet",
    "pip_expand": "Agrandir",
    "pip_close": "Fermer",
    "remote_title": "TÉLÉCOMMANDE TV",
    "remote_close": "Fermer télécommande",
    "remote_up": "Haut",
    "remote_down": "Bas",
    "remote_left": "Gauche",
    "remote_right": "Droite",
    "remote_dpad_up": "Haut",
    "remote_dpad_down": "Bas",
    "remote_dpad_left": "Gauche",
    "remote_dpad_right": "Droite",
    "remote_ok": "OK",
    "remote_home": "Accueil",
    "remote_live_tv": "TV en Direct",
    "remote_radar": "Radar",
    "remote_search": "Recherche",
    "remote_quick_channels": "CANAUX RAPIDES TV",
    "remote_instructions": "Utilisez les flèches du pavé directionnel et OK pour naviguer",
    "home_live_conditions": "Conditions météorologiques en direct",
    "home_last_updated": "Dernière mise à jour: %1$s",
    "home_wind_gusts": "Rafales de vent",
    "home_uv_index_label": "Indice UV",
    "home_active_alert_banner_prefix": "ALERTE ACTIVE:",
    "home_hourly_synoptic_strip": "CHRONOLOGIE SYNOPTIQUE SUR 12 HEURES",
    "home_saved_stations": "STATIONS TV FAVORITES",
    "home_manage_stations": "GÉRER",
    "home_vod_featured": "REPORTAGES VOD EN VEDETTE",
    "home_view_all_vod": "TOUT VOIR VOD",
    "home_view_protocol": "VOIR PROTOCOLE",
    "home_card_radar_title": "Radar Doppler Dual-Pol",
    "home_card_radar_desc": "Balayage Doppler de réflectivité en direct",
    "home_badge_layers": "4 COUCHES",
    "home_card_forecast_title": "Perspectives à 14 jours",
    "home_card_forecast_desc": "Modèles synoptiques détaillés",
    "home_badge_days": "14 JOURS",
    "home_card_vod_title": "Archives de terrain VOD",
    "home_card_vod_desc": "Chasses aux orages & études climatiques",
    "home_badge_vod": "VOD 1080P",
    "home_carousel_title": "PROGRAMME & ROTATION RADAR",
    "home_carousel_switch": "CHANGER DE VUE",
    "home_featured_stories": "INVESTIGATIONS DE TERRAIN EN VEDETTE",
    "home_all_stories": "TOUS LES REPORTAGES",
    "home_live_badge": "À L'ANTENNE",
    "home_studio_center": "Centre de commandement Horizon TV • Opérations radar nationales",
    "home_meteorologist_duty": "MÉTÉOROLOGUE EN SERVICE",
    "home_continuous_broadcast": "Diffusion continue multi-régionale radar et télémétrie",
    "home_switch_broadcast": "CHANGER LA DIFFUSION",
    "home_presented_by": "PRÉSENTÉ PAR LE DR. SARAH CHEN",
    "home_news_ticker_prefix": "FIL D'INFOS",
    "home_local_microclimate": "TÉLÉMÉTRIE MICROCLIMATIQUE LOCALE",
    "home_now_badge": "MAINTENANT",
    "home_feels_like": "Ressenti %1$s",
    "home_wind_label": "Vitesse du vent",
    "home_humidity_label": "Humidité",
    "home_aqi_label": "Qualité de l'air",
    "home_diurnal_breakdown": "RÉPARTITION DIURNE (12 PROCHAINES HEURES)",
    "home_rain_chance": "Pluie %1$d%%",
    "home_wind": "Vent",
    "home_humidity": "Humidité",
    "home_barometer": "Baromètre",
    "home_dew_point": "Point de rosée",
    "home_air_quality": "Qualité de l'air",
    "home_audio": "Audio",
    "forecast_title": "Prévisions atmosphériques synoptiques & micro-télémétrie",
    "forecast_subtitle": "Modèles complets à 14 jours, tendances horaires et micro-capteurs en temps réel",
    "forecast_tab_five_day": "Prévisions 5 jours",
    "forecast_tab_hourly": "Tendances 24h",
    "forecast_tab_astronomy": "Céleste & Lunaire",
    "forecast_tab_telemetry": "Télémétrie en Direct",
    "forecast_tab_extended": "Perspectives 14 jours",
    "forecast_fourteen_day_header": "PERSPECTIVES MÉTÉOROLOGIQUES À 14 JOURS",
    "forecast_meteorological_outlook": "PERSPECTIVES MÉTÉOROLOGIQUES",
    "forecast_numerical_prediction": "Modèles de prévision numérique et télémétrie en temps réel",
    "forecast_tab_5day": "Prévisions 5 jours",
    "forecast_tab_36hour": "Tendances 24h",
    "forecast_tab_24hour": "Céleste / Lune",
    "forecast_tab_14day": "14 Jours Étendu",
    "forecast_rain_risk": "Probabilité de précipitations",
    "forecast_atmospheric_deepdive": "ANALYSE APPROFONDIE DE LA TÉLÉMÉTRIE ATMOSPHÉRIQUE",
    "forecast_relative_humidity": "Humidité relative",
    "forecast_dew_point": "Point de rosée",
    "forecast_surface_pressure": "Pression de surface",
    "forecast_high_pressure": "Haute pression • Dégagé",
    "forecast_low_pressure": "Basse pression • Surveillance orage",
    "forecast_uv_index": "Rayonnement solaire UV",
    "forecast_uv_of_11": "sur indice 11+",
    "forecast_uv_very_high": "Rayonnement très élevé",
    "forecast_uv_high": "Rayonnement élevé",
    "forecast_uv_moderate": "Modéré",
    "forecast_uv_low": "Faible / Sûr",
    "forecast_wind_gust_vector": "Vecteur vent et rafales",
    "forecast_peak_gusts": "Rafales max: %1$s",
    "forecast_atmospheric_visibility": "Visibilité atmosphérique",
    "forecast_clear_horizon": "Horizon dégagé",
    "forecast_reduced_visibility": "Visibilité réduite",
    "forecast_cloud_cover": "Couverture nuageuse",
    "forecast_sky_observation": "Observation du ciel",
    "forecast_granular_table": "TABLEAU DÉTAILLÉ DU MODÈLE À 5 JOURS",
    "forecast_hum": "Hum: %1$d%%",
    "forecast_14day_extended": "PERSPECTIVES MÉTÉOROLOGIQUES À 14 JOURS",
    "forecast_rain": "Pluie %1$d%%",
    "radar_title": "Radar Doppler Dual-Pol Interactif",
    "radar_subtitle": "Télémétrie en direct et réflectivité • Station: KOKX NEXRAD • Centré sur %1$s",
    "radar_layer_precip": "Précipitations",
    "radar_layer_traffic": "Axes routiers",
    "radar_layer_satellite": "Satellite IR",
    "radar_layer_wind": "Lignes de flux du vent",
    "radar_legend_precip_title": "RÉFLECTIVITÉ (dBZ)",
    "radar_legend_traffic_title": "VITESSE DU TRAFIC",
    "radar_legend_satellite_title": "TEMPÉRATURE SOMMET NUAGES IR",
    "radar_legend_wind_title": "VITESSE DE FLUX",
    "radar_legend_precip_light": "20-30 dBZ (Pluie légère)",
    "radar_legend_precip_mod": "35-45 dBZ (Modérée)",
    "radar_legend_precip_heavy": "50-60 dBZ (Forte / Orage)",
    "radar_legend_precip_hail": "65+ dBZ (Risque de grêle)",
    "radar_legend_traffic_fast": "65+ mph (Fluide)",
    "radar_legend_traffic_mod": "35-50 mph (Modéré)",
    "radar_legend_traffic_slow": "< 20 mph (Fort ralentissement)",
    "radar_legend_sat_cirrus": "-20°C (Cirrus)",
    "radar_legend_sat_frontal": "-45°C (Nuages frontaux)",
    "radar_legend_sat_core": "-65°C (Cœur convectif profond)",
    "radar_legend_wind_vector": "Direction et vitesse du vecteur",
    "radar_zoom_in": "Zoom avant",
    "radar_zoom_out": "Zoom arrière",
    "radar_recenter": "Recentrer",
    "livetv_next_periods": "PROCHAINES SESSIONS EN DIRECT",
    "livetv_live_broadcast": "DIFFUSION EN DIRECT",
    "livetv_doppler_specs": "DOPPLER DUAL-POL 500KW DIRECT",
    "livetv_audio_on": "AUDIO ACTIVÉ",
    "livetv_muted": "MUET",
    "livetv_pip_mode": "MODE PiP",
    "livetv_presenter_name": "PRÉSENTATRICE: DR. SARAH CHEN",
    "livetv_presenter_subtitle": "Centre national des radars météorologiques • Télémétrie Doppler directe",
    "search_header_title": "Recherche mondiale de stations météorologiques",
    "search_header_subtitle": "Accédez aux radars et à la télémétrie de plus de 200 000 municipalités dans le monde",
    "search_placeholder": "Entrez ville, région ou pays (ex. Paris, Londres, Tokyo)...",
    "search_gps_button": "GÉOLOCALISATION GPS",
    "search_results_title": "RÉSULTATS DE RECHERCHE (%1$d)",
    "search_no_results": "Aucune station météorologique trouvée pour \"%1$s\"",
    "search_saved_title": "STATIONS FAVORITES ENREGISTRÉES (%1$d)",
    "search_saved_subtitle": "ENREGISTRÉ SUR LE PROFIL LOCAL",
    "search_active_badge": "ACTIF",
    "settings_header_title": "Préférences de diffusion et configuration",
    "settings_header_subtitle": "Personnalisez la présentation TV, les unités météo et les flux matériels",
    "settings_cat_display": "ESTHÉTIQUE D'AFFICHAGE & DIFFUSION",
    "settings_crt_title": "Lignes de balayage CRT et vignetage",
    "settings_crt_subtitle": "Effet cathodique rétro authentique et assombrissement des bords",
    "settings_remote_title": "Télécommande TV virtuelle",
    "settings_remote_subtitle": "Activer le pavé directionnel flottant pour TV",
    "settings_cat_units": "UNITÉS MÉTÉOROLOGIQUES & ÉCHELLES",
    "settings_units_title": "Unités de température & atmosphère",
    "settings_units_subtitle": "Préférences enregistrées localement et conservées entre lancements",
    "settings_saved_locally": "ENREGISTRÉ LOCALEMENT",
    "settings_celsius_title": "Celsius (°C)",
    "settings_celsius_subtitle": "Métrique: °C, km/h, mm, hPa",
    "settings_fahrenheit_title": "Fahrenheit (°F)",
    "settings_fahrenheit_subtitle": "Impérial: °F, mph, in, inHg",
    "settings_cat_audio": "CONTRÔLES AUDIO & DIFFUSION",
    "settings_audio_title": "Flux audio en direct 24/7",
    "settings_audio_subtitle": "Ambiance sonore atmosphérique et commentaires météorologiques",
    "settings_cat_civil": "SÉCURITÉ CIVILE & PROTOCOLES D'URGENCE",
    "settings_ebs_title": "Test du système d'alerte d'urgence (EBS)",
    "settings_ebs_subtitle": "Simuler une alerte urgente de tornade / orage violent",
    "settings_ebs_btn": "DÉCLENCHER LE TEST",
    "settings_cat_system": "SYSTÈME & FLUX DE TÉLÉMÉTRIE",
    "settings_sys_platform": "Moteur de plateforme",
    "settings_sys_provider": "Fournisseur principal",
    "settings_sys_radar": "Cœur radar",
    "settings_sys_astronomy": "Calculs astronomiques",
    "settings_sys_interval": "Intervalle d'alerte d'urgence",
    "vod_title": "ARCHIVES VIDÉO À LA DEMANDE (VOD) HORIZON",
    "vod_subtitle": "Reportages météo sur le terrain, traques d'orages et études climatologiques",
    "vod_badge_4k": "DIFFUSION 4K / 1080P",
    "vod_quality_badge": "DIFFUSION 4K / 1080P",
    "vod_more_category": "DANS LA MÊME CATÉGORIE",
    "vod_more_in_category": "DANS LA MÊME CATÉGORIE",
    "vod_streaming_status": "DIFFUSION DU FLUX MASTER 1080P",
    "vod_streaming_feed": "DIFFUSION DU FLUX MASTER 1080P",
    "vod_paused_status": "EN PAUSE",
    "vod_paused": "EN PAUSE",
    "vod_produced_by": "PRODUIT PAR HORIZON NETWORKS",
    "vod_published": "PUBLIÉ: %1$s",
    "vod_cat_all": "Tous les reportages",
    "vod_cat_severe": "Météo extrême",
    "vod_cat_forecasts": "Prévisions",
    "vod_cat_science": "Sciences de la Terre",
    "vod_cat_earth_sci": "Sciences de la Terre",
    "vod_cat_climate": "Climat & Nature",
    "astro_title": "HORIZON CÉLESTE & LUNAIRE",
    "astro_synodic": "CYCLE SYNODIQUE RÉEL",
    "astro_sunrise": "Lever du soleil %1$s",
    "astro_sunset": "Coucher du soleil %1$s",
    "astro_daylight_progress": "Progression diurne: %1$d%% de l'arc solaire écoulé",
    "astro_night_horizon": "Nuit: le Soleil est actuellement sous l'horizon local",
    "astro_illumination": "Illumination %1$d%%",
    "astro_days_to_full": "%1$d jours avant la prochaine Pleine Lune",
    "telemetry_header_title": "TÉLÉMÉTRIE DES CAPTEURS ATMOSPHÉRIQUES EN TEMPS RÉEL",
    "telemetry_live_status": "Flux local en direct • Échantillonnage actif (toutes les 2.0s) • Cycle #%1$d",
    "telemetry_paused_status": "Flux de télémétrie en pause",
    "telemetry_btn_pause": "PAUSE",
    "telemetry_btn_resume": "REPRENDRE",
    "telemetry_temperature": "TEMPÉRATURE",
    "telemetry_humidity": "HUMIDITÉ",
    "telemetry_barometer": "BAROMÈTRE",
    "telemetry_temp_chilly": "Frais / Froid",
    "telemetry_temp_mild": "Confort doux",
    "telemetry_temp_warm": "Chaud",
    "telemetry_temp_heat": "Forte chaleur",
    "telemetry_hum_dry": "Air sec",
    "telemetry_hum_ideal": "Confort idéal",
    "telemetry_hum_humid": "Humide",
    "telemetry_hum_high": "Forte humidité",
    "telemetry_press_low": "Basse (Vigilance orage)",
    "telemetry_press_normal": "Normale (Stable)",
    "telemetry_press_high": "Haute (Ciel dégagé)",
    "recharts_badge": "VISUALISATION GRAPHIQUE",
    "recharts_title": "PRÉVISIONS MÉTÉOROLOGIQUES SYNOPTIQUES À 5 JOURS",
    "recharts_subtitle": "Courbes de température, grille cartésienne et barres de probabilité de pluie",
    "recharts_tab_all": "TOUT",
    "recharts_tab_temp": "TEMP",
    "recharts_tab_rain": "PLUIE",
    "recharts_today": "AUJOURD'HUI",
    "recharts_legend_high": "Courbe temp max (%1$s)",
    "recharts_legend_low": "Courbe temp min (%1$s)",
    "recharts_legend_pop": "Probabilité de pluie (POP %%)",
    "recharts_hint": "CLIQUEZ SUR UN JOUR POUR AFFICHER LES DÉTAILS",
    "trends_title": "Courbe de température et précipitations sur 24 heures",
    "trends_temp_legend": "Temp (%1$s)",
    "trends_rain_legend": "POP pluie (%%)",
    "loading_sync": "SYNCHRONISATION DE LA TÉLÉMÉTRIE HORIZON...",
    "loading_connecting": "Connexion aux réseaux Open-Meteo & Radar Doppler",
    "error_signal_interrupted": "Signal de diffusion interrompu",
    "error_reconnect_button": "RECONNECTER LA TÉLÉMÉTRIE"
})

write_strings_xml("es", es)
write_strings_xml("fr", fr)
print("Group 1 base written")
